openapi: 3.0.3
info:
  title: Trip Planning API
  version: 1.0.0

tags:
  - name: Trip
  - name: User
  - name: Auth
    
paths:
  /:
    post:
      tags:
        - Trip
      summary: Add a new trip
      operationId: addTrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'   
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
        - user_auth: []
    get:
      tags:
        - Trip
      summary: Get all trips
      operationId: getAllTrips
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
                
  /{tripId}:
    get:
      tags:
        - Trip
      summary: Find a trip by ID
      operationId: getTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
    put:
      tags:
        - Trip
      summary: Update an existing trip
      operationId: updateTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'   
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
        - user_auth: []
    delete:
      tags:
        - Trip
      summary: Deletes a trip
      operationId: deleteTrip
      parameters:
        - name: tripId
          in: path
          description: Id of the trip
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'   
        '404':
          description: Trip not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
        - user_auth: []
  
  /budget:
    get:
      tags:
        - Trip
      summary: Find trips by budget
      operationId: getTripsByBudget
      parameters:
        - name: startDate
          in: query
          description: the starting date
          required: true
          schema:
            type: string
        - name: endDate
          in: query
          description: the ending date
          required: true
          schema:
            type: string
        - name: budget
          in: query
          description: the budget
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  allOf:
                    - $ref: '#/components/schemas/Trip'
                    - type: object
                      properties:
                        total_price:
                          type: integer
                        exchange_rate:
                          type: number
                        meals:
                          type: array
                          items:
                            type: string
                        weather:
                          type: array
                          items:
                            type: object
                            properties:
                              day:
                                type: number
                              min:
                                type: number
                              max:
                                type: number
                              night:
                                type: number
                              eve:
                                type: number
                              morn:
                                type: number
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []

  /country:
    get:
      tags:
        - Trip
      summary: Find trips by country
      operationId: getTripsByCountry
      parameters:
        - name: startDate
          in: query
          description: the starting date
          required: true
          schema:
            type: string
        - name: endDate
          in: query
          description: the ending date
          required: true
          schema:
            type: string
        - name: destCountry
          in: query
          description: destination country
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  allOf:
                    - $ref: '#/components/schemas/Trip'
                    - type: object
                      properties:
                        total_price:
                          type: integer
                        exchange_rate:
                          type: number
                        meals:
                          type: array
                          items:
                            type: string
                        weather:
                          type: array
                          items:
                            type: object
                            properties:
                              day:
                                type: number
                              min:
                                type: number
                              max:
                                type: number
                              night:
                                type: number
                              eve:
                                type: number
                              morn:
                                type: number
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
                
  /user:
    post:
      tags:
        - User
      summary: Add a new user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'   
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User Already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
        - user_auth: []
    get:
      tags:
        - User
      summary: Get the current User
      operationId: getCurrentUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      security:
        - api_key: []
                
  /getkey:
    get:
      tags:
        - Auth
      summary: Get authentification key
      operationId: getkey
      parameters:
        - in: header
          name: client_id
          schema:
            type: string
          required: true 
        - in: header
          name: secret
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  key: 
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /logout:
    get:
      tags:
        - Auth
      summary: Logout
      operationId: logout
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
                
  /login:
    post:
      tags:
        - Auth
      summary: Find a trip by ID
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - api_key: []
components:
  schemas:
    Trip:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        city:
          type: string
        country:
          type: string
        ticket:
          type: integer
        daily_accommodation:
          type: integer
        daily_food:
          type: integer
        daily_miscellaneous:
          type: integer
        image:
          type: string
        currency:
          type: string
          readOnly: true
    User:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        username:
          type: string
        password:
          type: string
          writeOnly: true
    Error:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
          
  securitySchemes:
    user_auth:
      type: http
      scheme: bearer
    api_key:
      type: apiKey
      name: api_key
      in: header
          